### ISSUE TITLE
treat 3D cubes with a single channel as 2D images

### ISSUE THREAD

**Issue by veggiesaurus** [idia-astro/cpp_hdf5converter#1]
At the moment, the converter treats a 3D (or 4D) cube with a single channel as a 3D cube. This means the following are all generated:
- rotated datasets
- Z statistics 
- XYZ statsitics (same as XY statistics)

These should not be created when only a single channel is present. We could either:
- simply convert the image to a 2D image, which would simplify things significantly, but prevent exact round-trip FITS conversion (not that this seems to be too much of an issue at the moment)
- keep the image as is, but just not calculate these additional datasets

**Comment by confluence** [comment]
I believe that the Python converter already skips these datasets, and I think that the C converter should do the same thing. I don't think that we should change dimensions of images that we convert, or at least it should not be the default behaviour. Perhaps we could add an option later to strip axes.
