### ISSUE TITLE
losing precision in hdf5 image after conversion from fits

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/cpp_hdf5converter#23]
with 

> SCHEMA_VERSION = 0.3
HDF5_CONVERTER = hdf_convert
HDF5_CONVERTER_VERSION = 0.1.10

> git branch
\* dev
[root@almat1 cpp_hdf5converter]# git log
commit a833d1c0d9a4ca52917da5a66766009f40bad731
Author: Adrianna Pińska <adrianna.pinska@gmail.com>
Date:   Fri Feb 21 17:36:29 2020 +0200
    Fixed off-by-one error which was causing the last entry in every header to be dropped.

we see
![Screen Shot 2020-04-14 at 5 47 12 PM](https://user-images.githubusercontent.com/20819712/79210856-07c8d900-7e78-11ea-92c1-48b8e1236902.png)

Its fits is
![Screen Shot 2020-04-14 at 5 47 23 PM](https://user-images.githubusercontent.com/20819712/79210897-11ead780-7e78-11ea-9b88-fa729f14f5c5.png)

We can see, for example, BMAJ and BMIN are truncated. Same for CRVAL1 and CRVAL2 so that the the reference world coordinate has an offset comparing to fits.

**Comment by confluence** [comment]
I will look into this. Can you share the file that you used to test this?

**Comment by kswang1029** [comment]
please try https://drive.google.com/open?id=1GBkof53vxeJb4GfELAj1_uIwJzOyxJqf

**Comment by confluence** [comment]
It looks like the values are fine in the file, which becomes clear when you change the precision used by `h5dump` to display floating point values (using a secret flag which is documented in the help but not the man page for some reason):
```
$ fitsheader ../fits/M17_SWex.fits | grep -E 'BMIN|BMAJ'
BMAJ    =   5.725136068132E-04                                                  
BMIN    =   4.142385721207E-04

$ h5dump -m "%.15e" -A M17_SWex.hdf5 | grep -E -A6 'BMIN|BMAJ'
      ATTRIBUTE "BMAJ" {
         DATATYPE  H5T_IEEE_F64LE
         DATASPACE  SCALAR
         DATA {
         (0): 5.725136068132000e-04
         }
      }
      ATTRIBUTE "BMIN" {
         DATATYPE  H5T_IEEE_F64LE
         DATASPACE  SCALAR
         DATA {
         (0): 4.142385721207000e-04
         }
      }
```

So this is a display bug either in the backend or the frontend. I previously fixed a related issue in the backend (in the code which was converting HDF5 attributes back into a FITS header), and I thought that it was fixed everywhere, but I must have missed something. I'll check where this is happening.

Have you observed any differences anywhere other than the info in the file browser?

**Comment by kswang1029** [comment]
> Have you observed any differences anywhere other than the info in the file browser?

I will keep trying to observe. The first step to do is to regenerate hdf5 images with the updated converter. Is it okay to do so now with the current dev version of the converter?

**Comment by confluence** [comment]
Yes, it is. This issue should be unaffected, but we fixed a few other conversion bugs, so it's a good idea.

**Comment by kswang1029** [comment]
Will do 👍

**Comment by kswang1029** [comment]
as a note, I created a backend issue for this.
https://github.com/CARTAvis/carta-backend/issues/494

**Comment by confluence** [comment]
This issue has been reopened [in the backend repo](https://github.com/CARTAvis/carta-backend/issues/494).
