### ISSUE TITLE
Improve converter output

### ISSUE THREAD

**Issue by confluence** [idia-astro/cpp_hdf5converter#24]
A lot of the output is currently cryptic or incomplete. It could be a lot better.

* Calculate and print out the full expected memory allocation, including all extra datasets. The current output only reports the main and swizzled dataset allocations, which is really confusing.
* Clean up the timing subsections; don't print unused / zero sections.
* Check where mipmap timing is filed and update the appropriate descriptions.
* The timing subcategories don't add up to the totals, which is also confusing. Consider which timing numbers are actually useful and important.

Edit: additionally, we need verbose output, especially in the slow mode, to assist in debugging.

**Comment by Jordatious** [comment]
As discussed via Slack, there's also the `????` that may need to be fixed up (see below). And it would be useful to display the total memory required/requested.

```
Allocated in 1.636 seconds (23393.3 MB/s)
Read in 204.783 seconds (186.888 MB/s)
Processed in 3099.29 seconds (12.3485 MB/s)
        XY, XYZ & Z stats: 1796.91
        Histograms: 450.602
        Swizzling: 851.781
        ????: 0
Written in 238.193 seconds (160.674 MB/s)
TOTAL: 3543.9 seconds (10.7992 MB/s)
```
