### ISSUE TITLE
expand stats types

### ISSUE THREAD

**Issue by veggiesaurus** [idia-astro/cpp_hdf5converter#3]
XY and XYZ stats should switch from storing `mean` to storing `sum` and `sumX2`. This will allow us to reconstruct the following:
- mean values (from `sum` and `nan_count` values)
- std deviation (from `sum`, `nan_count` and `sumX2` values)
- rms (from `sumX2` and `nan_count`)

This will be helpful when viewing image stats in CARTA.

**Comment by confluence** [comment]
This has been done in the `dev` branch. We shouldn't merge it to `master` until CARTA can handle the new schema.
