### ISSUE TITLE
hdf5 header missing "name"

### ISSUE THREAD

**Issue by acdo2002** [idia-astro/cpp_hdf5converter#41]
When we check the image "M17_SWex.hdf5" header (hdf5 converter version: 0.1.13), we realize there is a line in
fileInfoResponse.fileInfoExtended['0'].headerEntries shows 
{ value: "1", entryType: 2, numericValue: 1 }

Could it modify to 
{ name:"", value: "1", entryType: 2, numericValue: 1 }
Even given it an empty name or other proper description (I prefer to give a description, then user would be easier to trace what is it) would be good.

**Comment by veggiesaurus** [comment]
@acdo2002 do you have the original FITS image? @confluence can you look into why the name is being ignored?

**Comment by confluence** [comment]
This is not a converter issue. There are no attributes without names in the HDF5 file. You can confirm this with `h5dump`.

You are looking at header entries which have been computed in the backend. Please file this as a backend issue and close this one.

**Comment by acdo2002** [comment]
@veggiesaurus 
I put it on google [drive ](https://drive.google.com/drive/folders/1qj53HcB_6KNjQcxWM_gKhwh0ybqNXmFI?usp=sharing). Or going to [carta-backend-ICD-test](https://github.com/CARTAvis/carta-backend-ICD-test) code:public/set_QA/M17_SWex.hdf5.zip, there also provides the image we tested (hdf5 converter version 0.1.13).

@confluence Thanks for checking this, I will post it on the carta-backend issue and close fit2idia issue.
