### ISSUE TITLE
Add per-host configurable memory use limit

### ISSUE THREAD

**Issue by confluence** [idia-astro/cpp_hdf5converter#43]
~Create and package a separate executable which can only estimate memory, so that it can be installed on login nodes where no calculation should take place.~

Add a configurable memory use limit, which may be zero.

**Comment by veggiesaurus** [comment]
Counter suggestion: config file that limits the maximum size of cube to be converted, or the maximum memory allocatable. Could be set to zero to prevent any conversion

**Comment by confluence** [comment]
Good point; this could be configured per-machine.

**Comment by Jordatious** [comment]
Would this be part of the package itself? But editable by a system admin? I suppose that could work, although the only other advantage for ilifu (other than implementation) would be setting a different value for the two HighMem nodes compared to all the other nodes. However, what's really relevant is limiting it to whatever the user has been allocated for the job, which, on ilifu, is something already done by cgroups on the nodes.

**Comment by veggiesaurus** [comment]
@Jordatious yes, editable by the system admin, or anyone who has write access to the config folder (`/etc/fits2idia/config` perhaps?)

This would allow you to have highMem nodes with a different config.

**Comment by Jordatious** [comment]
Yeh that could work. What do you think @jeremysmith123?
