### ISSUE TITLE
Issue a version tag and a release on Github

### ISSUE THREAD

**Issue by ajm-ska** [idia-astro/cpp_hdf5converter#47]
We have created an AppImage of fits2idia for the benefit of Ubuntu and RedHat users who may not have root access.
The best place to host it would be right here on the repository as a release.

Doing so would also provide a 'tag' with a version number. There are currently no tags although the current version appears to be version 0.1.15. Having a proper tag would make it easier to produce a Homebrew version.

**Comment by ajm-ska** [comment]
Regarding the Homebrew version, we would put the fits2idia.rb formula in the `cartavis/homebrew-tap` repository. Then to install it, the user would simply enter:
 
```
brew install cartavis/tap/fits2idia
```

Or if they had previously installed anything from cartavis/tap, then it would be simply `brew install fits2idia`. But for simplicity, I guess we can just say `brew install cartavis/tap/fits2idia`.

**Comment by confluence** [comment]
We should also edit the README to explain the different installation options.

**Comment by confluence** [comment]
This is done (instructions added in #48).
