### ISSUE TITLE
left clicking on pixel inside a region does not centre the image

### ISSUE THREAD

**Issue by arusstaylor** [idia-astro/cpp_hdf5converter#5]
Normally when I left click on a pixel in an image the image recenters to place that pixel at the centre of the display.  If the pixel is inside a region box this does not work.  Clicking on a pixel inside a region box does nothing.

**Comment by veggiesaurus** [comment]
@arusstaylor can you file this issue in the frontend repository? When you click inside a region box, it selects the region. This is the expected behaviour, and there's a science team question relating to this. For centering the image inside a region, you can use middle-click or ctrl/cmd + click.
